spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # base
    url: jdbc:shardingsphere:classpath:conf/config-sharding-local.yaml
  
  # local
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#    username: root
#    password: root

server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zc.example.entity
  type-enums-package: com.zc.example.enums

logging:
  config: classpath:logback.xml
  level:
    com.zc.example.mapper: debug
